#version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: local_postgres_db
    restart: unless-stopped
    env_file:
      - ../../.env # Carga las credenciales desde la raíz del proyecto
    environment:
      - POSTGRES_USER=${DB_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - local_stack # Solo n8n necesita verlo

  n8n:
    image: n8nio/n8n:latest
    container_name: local_n8n
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - ../../.env # Carga las credenciales desde la raíz del proyecto
    environment:
      # --- Conexión a Postgres ---
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres # <-- Habla por nombre de servicio
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${DB_POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRES_PASSWORD}
      
      # --- Configuración Local (Sin Traefik/SSL) ---
      - NODE_ENV=production
      - N8N_HOST=sanctionless-abdiel-mincingly.ngrok-free.dev
      - N8N_PORT=5678
      - N8N_PROTOCOL=https 
      - N8N_WORKFLOW_DIR=/workflows
      - WEBHOOK_URL=https://sanctionless-abdiel-mincingly.ngrok-free.dev # <-- Clave para webhooks
      - TZ=${TZ}
      
    ports:
      - "5678:5678" # <-- Mapea n8n a http://localhost:5678
      
    volumes:
      - n8n_data:/home/node/.n8n
      - /Users/diego/Sync/workflows/n8n:/workflows
    networks:
      - local_stack

  qdrant:
    image: qdrant/qdrant:latest
    container_name: local_qdrant
    restart: unless-stopped
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - local_stack
    ports:
      - "6333:6333" # <-- Mapea Qdrant a http://localhost:6333
      - "6334:6334" # <-- Mapea gRPC a http://localhost:6334

volumes:
  db_data:
  n8n_data:
  qdrant_data:

networks:
  local_stack: # Una sola red interna para todos
    driver: bridge
